### PR TITLE
Discord plugin refactoring for Python 3.5

### PR DESCRIPTION
**Pull request by evonzee**
This PR reorganizes the Discord plugin to work with the latest version of the library.  With the current API, this version can only read mesages in Discord if the bot is @tagged, but it's better than nothing.  Subsequent PRs to come for an upgrade to Python 3.11 and the latest Discord bot, which resolves this issue.

It also adds github actions support to build and publish a docker image and cleans up a few warnings we were seeing on our server.  Some of this code is several years old at this point, so I've somewhat lost track of why the changes were made.  Please feel free to bring up any concerns.

### CODE REVIEW

**Review by medeor413 — APPROVED** [review]
I've read through this all and I can't see anything to complain about. Before I merge this, though, I have to ask - is this PR necessary if #150 is merged? I note that the other PR also includes a Discord bot rewrite and many of the same commits.

**Comment by thakyZ** [comment]
Wow thanks, my work was cut out for me 5 years ago 😂

**Comment by evonzee** [comment]
@medeor413 No, this PR is the base for #150.  If you take #150 this is unneeded.  I separated them as I wasn't sure if you wanted to move your codebase to require python 3.11 as my branch does and I wanted to offer you both the 3.5 fixes as well as the full boat upgrade independently.

**Comment by medeor413** [comment]
Okay, super. I'll be closing this, then.

**Pull request closed without merging**
