### PR TITLE
Updated and fixed Discord Bot and IRC Bot code

### PR DESCRIPTION
**Pull request by thakyZ**
Updated the code for Discord Bot and fixed some errors that will throw if you don't have the irc bot enabled.

### CODE REVIEW

**Comment by ren-kun** [comment]
Hello,

Have you tested the bot? If possible can you take up the project? I can help out with bounties etc

**Comment by thakyZ** [comment]
I have tested the bot and it does work. Sadly I am in school and I cannot exactly take up the project right now.

**Comment by thakyZ** [comment]
So I may have thought I fixed the async functions, but I am not at all experienced with async in python, in fact I barely know python. So I can't say for sure that I got the async functions to work, but since `yield from` cannot be used in a async function anymore and you cannot use the `@asyncio.coroutine` anymore I tried to compromise, if you, @ren-kun, have any input to this, that would be great. But I don't think I can manage this project full time, I understand that you cannot either, but I have a lot on my plate and I can make updates every once and a while but if you don't mind adding me as a maintainer I can update it as best as I can.

**Comment by thakyZ** [comment]
I did not mean to close this

**Comment by thakyZ** [comment]
I pushed some new changed and undid some of the older changes, because I realized the changes I made to update it to Python 3.8 would have not worked, and the entire code would need a re-write which I just don't know how to do. I will make a issue for a rewrite in hopes someone could do that.

**Comment by Rattle189** [comment]
Tested and working as of writing. Thank you for fixing this. Only minor problem is that every time a chat message is sent (from either Discord or the server), the console prints out this error:
`
2022-08-03 17:27:09 - ERROR - asyncio # Task exception was never retrieved
future: <Task finished coro=<IRCPlugin.bot_write() done, defined at /usr/local/lib/python3.5/asyncio/coroutines.py:208> exception=AttributeError("'NoneType' object has no attribute 'privmsg'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/app/plugins/irc_bot.py", line 372, in bot_write
    self.bot.privmsg(target, msg)
AttributeError: 'NoneType' object has no attribute 'privmsg'
`

**Comment by thakyZ** [comment]
@Rattle189 What version of Python are you using. Because newer versions of python than 3.6-7ish? have reworked async in the code and are not compatible, and I haven't had much of the time because of college to work on reworking and learning python async.

**Comment by Rattle189** [comment]
I'm using Python 3.5.9, the error being printed out doesn't seem to cause any issues whatsoever and has stopped. I'm not sure what was causing it previously but it hasn't returned now.

**Comment by medeor413** [comment]
Unnecessary with #150. Sorry I ghosted you for a few years 😅

**Pull request closed without merging**
