### PR TITLE
Feature/python 3.11

### PR DESCRIPTION
**Pull request by evonzee**
Modify codebase to support Python 3.11 and the latest discord library

### CODE REVIEW

**Review by medeor413 — APPROVED** [review]
Everything you've written here looks good. My only note would be the use of `asyncio.ensure_future` in several places while `asyncio.create_task` is now preferred for scheduling tasks.
This codebase needs a ton of modernization, and this is a good step in that direction. Approved, pending #149.

**Comment by evonzee** [comment]
Made some big changes to remove the remaining ensure_futures, including switching main to use asyncio.run(), standardizing on async Commands, handling backgrounding in send_message, and a few other tweaks.

**Review by medeor413 — APPROVED** [review]
Again, everything looks good. Thanks for going above and beyond.

**Comment by evonzee** [comment]
Awesome! Thanks, folks.  I'll be working on some other issues and will provide PRs as I do.

**Pull request merged**
