### PR TITLE
Feature/docker config

### PR DESCRIPTION
**Pull request by evonzee**
Hi folks,

I added a baseline dockerfile so I can run this project in a container.  Thought it might be useful for you as well.

Currently I am not doing anything fancy with volumes for the config/player db, though I think that would be valuable.  

I expect to have other PRs that will include these changes; let me know if you don't want these and I'll produce future PRs without them.

### CODE REVIEW

**Comment by kharidiron** [comment]
I like the idea of having a docker option as well, though I'd like to see it a bit more fleshed out/fully tested before we merge it in. Once you're relatively certain you don't need to make many further changes to the files, I'll be happy to merge it.

As another point to consider, we will eventually be retiring this build, as we are in the process of doing a from-scratch rebuild of the code base, keyed to Python 3.7 or later, and getting rid of some really bad design decisions. It isn't ready for production use yet, but it is where we are putting our efforts for future features.

**Comment by evonzee** [comment]
Interesting!  I don't see a likely branch in the upstream repo; Is that rebuild hosted in a different repository?  I'd be happy to build against that instead/as well.  

I'll update this PR with:

- Config volume
  - That will include not copying the config/*.default files into the container and relying on the first-time-run process to generate the files on volume.  
- Some usage documentation
- add irc3 for users of the irc plugin

I'll leave the (presumed) dockerhub setup to you as the project owner.

**Comment by medeor413** [comment]
Development is indeed occurring in [another repo](https://github.com/StarryPy/Project-Apophis), though all of the work is currently in forks right now, so there isn't terribly much to see there... Unfortunately we're still (re)building the base, so there isn't especially much to be done now, but your contributions would definitely be appreciated later. I'll sit down later today and see if I can get a reasonable bit of the framework done...

**Comment by DiNitride** [comment]
Is there any way that people (Me) that have been interested in the project
get involved with the rebuilding and design, one of the main reasons I
never got into anything on my fork is due to the project not having much
documentation.

I've also got a few questions/suggestions about the structure of the project

**Comment by evonzee** [comment]
Hi folks,

I think this branch is pretty stable at this point. We've got a (very lightly traffic'ed) test server that's been running it for a week or two, and I've been switching images using the volume support with no data loss thus far.  Any thoughts on next steps/review?  I've got a bunch of other feature branches waiting in the wings. :)

**Pull request closed without merging**
